### ISSUE TITLE
Circles; support for contributions to subset of the DHO

### ISSUE THREAD

**Issue by mgravitt** [hypha-dao/eosio-contracts#23]
The DHO needs support for circles.  Start to document scope and design here.

Use case:  a contribution is made to a subset of the DHO (e.g. a group of roles or an initiative).  I will refer to an initiative and circle interchangeably.

### Steps
Using "Light Food" as an example:

1.  A member contributes $50k USD with a contribution request for the resources to be used for the Light Food initiative.

2. When this proposal is submitted, the member specifies: 

     2.1.  The quantities of which tokens to be minted/allocated in exchange for the contribution (e.g. 50k HUSD, 25k HYPHA, xyz HVOICE, and/or SEEDS)

     2.2.  The name/identifier of the circle for which this contribution should be allocated (e.g. Light Food).

3. The proposal passes and BTC/USDT, etc goes into the Hypha treasury and the tokens specified in the proposal are **allocated** to the circle/initiative identifier  (at this point, the tokens are NOT transferred to a different account, but they are ear-marked in a table within ```dao.hypha``` contract)

     3.1.  Once allocated, these tokens can only be sent via proposals attributed to this circle.

     3.2.  There is no time-frame specified; the tokens remain until used.  (time-series/recurring budgets come later - much more complex!)

4. New proposals may select this circle when the proposal is created.

     4.1.  If the Light Food circle is selected when created, this proposal can only be voted on by members of the Light Food circle.  Members of the Light Food circle are only members who have an active assignment associated with this circle (so, roles/assignments also need a circle identifier).

    4.2.  When a member of the Light Food circle votes on this proposal, their entire HVOICE balance is assigned to their vote. 
 
    4.3.  The quorum is 20% of the HVOICE balance for the members with an active assignment in that circle.  The passing criteria is 80% alignment of the HVOICE balance for the same members.

5.  When proposals for this circle are passed, the tokens are sent from the circle allocation ONLY.

### Edge Cases 
- The full DHO has the power to **un-allocate** the tokens via a new proposal type.  (in the near-term, we may do this only via multisig/treasury)

- A circle proposal MAY send tokens to any account - the recipient does not need an assignment within that circle.  This aligns with way it works for the whole DHO.

-  It is very likely that proposals for this circle will be created that are greater than their current allocation (e.g. an assignment that goes for 6 months).  The proposal and assignment creation will NOT fail in this case.  However, if the funds run out, the payment claim will fail at that time.  This allows the circle to operate and plan on future contributions to their circle without having everything fail.  When more tokens are allocated to this circle, payment claims may resume where they left off.

- What if a circle wants to exchange their tokens or change the mix?  Hmmm... not allowed, or perhaps requires an un-allocation and re-allocation?

-  This model does NOT support assignments shared across multiple circles.  A member can of course have multiple assignments, but they are managed wholly separate with separate claim transactions.

-  Note that the voting power of a member within a circle is their full HVOICE balance regardless of their time commitment within that circle.  This creates a potential attack vector by allowing members far out-sized influence, as it's a function of their balance relative to the balance of the circles in which they have assignments.

**Comment by sceenius** [comment]
Ok, so we are collapsing circle creation and funds allocation into a single operation. I like that. It gives us tremendous flexibility to support circle activities from different sources of funds. This could also apply to editing circles (and suspending for that matter), methinks.

**Comment by julioholon** [comment]
Hey there! I just love the design! It's very much in alignment with what I call "Circle Buckets", similar to how Enspiral's Cobudget works.

Here are some thoughts/suggestions:
- Circles have to be proposed first, In order for you to be able to pick them in the UI, right?
- Regarding section 4, I think only Roles and Contribution should have Circle associated to them (not Assignments, as it could be confusing if a Role is created and voted at the context of one Circle and assigned to another), so if 2 Circles need the same Role it should be proposed and voted independently (because Roles belong and have an entire life inside the Circle, as its members can propose and vote changes to it).
- On 4.2, in my opinion, we should use 1Account/1Vote (or 1 person, 1 vote) within circle context, HVOICE should be used for Whole Hypha proposals only. And we should use 80% unity with at least 50% quorum (I would even go for 80% quorum, because we're taking about 5-8 people in that circle, that should be already aligned to the circle proposal)
- I like the idea that the full DHO has the power to **unallocate** that funds, maybe use a reverse Contribution request with negative numbers? How do you think about implementing that? Or it's just a multi-sig action?

**Comment by sceenius** [comment]
@juliolrmonteiro Great extension of our thinking. Let me elaborate on the basic structure of the DHO- 

We have

* Roles (role template) and role-assignments (role fillers)
* as well as contributions and going forward 
* Badges (badge template) and badge-assignment (badge holders)
* Circles and circle-assignments (circle members) AND/OR
* Accounts and account-assignments (account holders) 
* Policies and policy-assignments (policy holders)
* Quests and quest-assignments (quest members)
* Challenges and challenge-assignments (challenge fillers)

Now, the objects on the left are org assets, the ones on the right are costs/expenses bound to circles/accounts. We need flexibility to say _where an assignment or contribution is activated_, which can be in any circle (e.g. Tech "adopted" a Game of Hypha Ambassador role recently). If we bind role-templates to circles we loose that flexibility and there will be many copies of the same role to bring it into other circles. This might be ok for now, but going forward I plan to make roles more and more granular, focusing on a specific skillset needed so that we can use more of our talents across the org.  

But I have another idea about the circles.

**Comment by sceenius** [comment]
Your suggestion about 1A1V vs. 1T1V is valid and a signal that the circle governance needs more work. 

I propose to separate the accounts/allocations/funds from the circle structure. 

In a nutshell, each assignment and contribution requires an allocation of funds == account. We will create accounts for each circle as well as other accounts that we don't know about yet (e.g. special grants & gifts, crowdsourced funds, emergency funds, investor accounts, product accounts, shared accounts, there are lots of possibilities and we open up a very large possibility space here). 

The only change we need to do on the UI/UX is to assign each assignment and contribution to an account. I think @dappdever had the same idea about this. The accounts are managed by the treasury and used in the budgeting process. There are special "circle account" that mimics our root level circle structure - or not - as we saw, this structure is still changing and the reason to keep our accounting separate from the org structure that is still evolving.

This would also mean we can remove the "capacity" field from roles since you can apply for a role as long as the budget/funds are sufficiently covered (we can align with a projected 3-mo or 6-mo assignment period). So, all of these org assets can exist/be defined/be proposed and voted in and only if they get "executed" will funds be needed. That's an elegant way to chose which kind of role (quest/challenge) fits best into our current situation (I recently talked about "job jars" to incentivize participation, similar to the #inbox concept in the ST circle).

**Comment by sceenius** [comment]
To continue with the governance model, if we go with sociocratic consent we can make most (if not all) circle decision off chain. That would mean we can export the entire holonic structure into another tool (aiming at Nestr here) and leave the circle dynamics to that environment. It's highly fluctuating and we need a tool that is able to respond to these changes _in real time_. The DHO will deal with the larger decisions (on org assets) only where your HVOICE plays a more significant role and not the day-to-day structural changes or localized circle decisions (on assignments/contributions). For the latter, we could enable the LL badge holder to make this decision (similar to the Enroller for new members).

**Comment by sceenius** [comment]
![image](https://user-images.githubusercontent.com/24725582/95689731-d2136b80-0be0-11eb-9953-267689bab7cf.png)

**Comment by joostschouten** [comment]
Risking stating the obvious. But beyond the lovely budgeting described here a circle would require:
- Name
- Purpose
- Accountabilities
- Domains (optional)
- Parent circle

**Comment by sceenius** [comment]
Yes, completely obvious and entirely in the hands of the right side (Nestr), with roles being at the intersection of the two.
