### ISSUE TITLE
Automatically close proposals

### ISSUE THREAD

**Issue by mgravitt** [hypha-dao/eosio-contracts#27]
The leading option to automatically close proposals is to place an entry in the seeds scheduler when the ballot/proposal is created. 

See TODO item here: https://github.com/hypha-dao/eosio-contracts/blob/master/src/decide.cpp#L66

The action to close a proposal is 
``` c++ 
ACTION closeprop(const uint64_t &proposal_id);
```

Since the proposal_id is not known until the object is written to RAM in the ```new_object``` function, we either need to refactor this quite a bit OR perform a look-ahead to find what the proposal_id will be.  Since we are replacing the functionality with both the document structure and native ballots in the future, I think performing the look-ahead is best.

Generally, the code would look like this: 

``` c++ 
// double-check that "rbegin()" really points to the last item (these IDs are always sequential)
object_table o_t (get_self(), name("proposal").value);
uint64_t next_proposal_id = o_t.rbegin().id+1;

// calculate action invocation time
config_table config_s(get_self(), get_self().value);
Config c = config_s.get_or_create(get_self(), Config());
time_point_sec schedule_time = time_point_sec(current_time_point().sec_since_epoch() +    // now
          c.ints.at("voting_duration_sec") +                // voting period from config
         300);                                                             // 5 minute buffer 

// action_to_schedule 
//    -  call  "closeprop" on the "dao.hypha" contract (get_self())
//    -  the "proposal_id" parameter for "closeprop" should be "next_proposal_id"
//    -  use "schedule_time" above as the time to make the invocation
```

**Comment by IanMendozaJaimes** [comment]
Hello Max, I have a question:
> The leading option to automatically close proposals is to place an entry in the seeds scheduler when the ballot/proposal is created.

When you say seeds scheduler do you mean literally the scheduler contract from the seeds' repository https://github.com/JoinSEEDS/seeds-smart-contracts ? 
If that's the case, I think it wouldn't be possible right now, because the seeds scheduler only supports actions with no parameters.
Would it be fine a deferred transaction instead?

**Comment by mgravitt** [comment]
> Hello Max, I have a question:
> 
> > The leading option to automatically close proposals is to place an entry in the seeds scheduler when the ballot/proposal is created.
> 
> 
> 
> When you say seeds scheduler do you mean literally the scheduler contract from the seeds' repository https://github.com/JoinSEEDS/seeds-smart-contracts ? 
> 
> If that's the case, I think it wouldn't be possible right now, because the seeds scheduler only supports actions with no parameters.
> 
> Would it be fine a deferred transaction instead?
> 
> 
> 
> 

Yes, that is what I was referring to. I didn't know that it doesn't support parameters. Deferred transaction is probably the best option then, although they are being deprecated, so we need a different long term solution. It'll probably be awhile though. Thanks

**Comment by IanMendozaJaimes** [comment]
I think a good option is to add the schedule_time to some proposal's content group, then with an action `closeprops` for instance, we can traverse the proposals document, and close the proposals that need to be closed. By doing so, it would be possible to use the seeds scheduler to execute `closeprops` periodically. 

A drawback, would be that it is needed to traverse the entire proposals document, is it possible to order proposals by schedule_time? If it is not, then I could traverse the proposals document using batches to avoid exceeding the execution time allowed per transaction.
Also to schedule an action in the seeds scheduler, it's necessary to have the scheduler contract's active authority, that's why I think it's better to just schedule one action that could be executed several times per day (that's how these kind of actions are executed in seeds). The `closeprops` action needs also a linkauth with the permission `execute` and then grant scheduler@active permission to authenticate hyphadao@execute authority.

I think either the deferred transaction or the schedule_time, should be added in the `new_proposal` method, because `register_ballot` is called by other two methods (`propose_badge` and `propose_badge_assigment`) that don't create any new proposals and as far as I concern they don't affect the object_table with proposal scope. But I could be wrong so I wanted to tell you that.

**Comment by mgravitt** [comment]
@IanMendozaJaimes there is no authority required to call ```closeprop``` or ```closedocprop```.  Any telos account can call it.  Since it will only execute based on the vote count, we figured it was fine not to secure it.  I think this will alleviate the need to add the scheduler's authority or any linkauth.  Is that right?

> NOTE: there are will be two types of ballots.  There is the old/current method that uses ```register_ballot```, which uses the telos decide contract.  The new method, not yet deployed, will use "native ballots", where the vote tally is stored in a document rather than telos decide.  The code for this is in the ```native-ballots``` branch.  This doesn't impact the scheduling of closing proposals but just wanted to make you aware. 

It isn't possible to order proposal documents by scheduled time. We can sort ALL documents by ```created_date``` desc and then check if they are proposals.  This isn't exactly what we want either, but might be the best option. 

### Perhaps this option?
Just spitballing here - Another option is to create a document/node that is linked from the ```root_node``` with an ```edge_name``` of ```schedule```.  Then, this document could have a ```content_group``` for each scheduled job (proposal hashes, etc).  Then, when creating a new proposal, we could add a ```content_group``` to this document and the schedule executer can remove the ```content_groups``` as they are executed.  

It could look like this: 
``` json
          [{
            "label": "content_group_label",
            "value": [
              "string",
              "scheduled_job"
            ]
          },{
            "label": "title",   /* this might not be needed, but perhaps for logging */
            "value": [
              "string",
              "Close proposal 1fc633347393d8ebf76ccd639da2e03d4934ffda4ff3f71211c648e53435e6ec"
            ]
          },{
            "label": "account",
            "value": [
              "name",
              "dao.hypha"
            ]
          },{
            "label": "action",
            "value": [
              "name",
              "closedocprop"
            ]
          },{
            "label": "proposal_hash",
            "value": [
              "checksum256",
              "1fc633347393d8ebf76ccd639da2e03d4934ffda4ff3f71211c648e53435e6ec"
            ]
          },{
            "label": "scheduled_time",
            "value": [
              "time_point",
              "2020-11-02T20:19:20.500"
            ]
          }]
```

#### Challenge with forks
One challenge with this approach is that we are still designing how updating and/or forking documents will work. The unique identifier of a document is the hash of its content groups (content-addressing).  When we update the content, we could update the hash and then update all of the edges that reference the hash to reference the new hash.  (in the case of the schedule, there would only be one hash)

Another idea we've been thinking through is forking similar to how git uses branches. A fork of a document would have a reference back to the parent and then hold only the diffs between it and its parent. In this case, retrieving the most recent version of a document would require recursing upwards through its lineage, which may not be practical. 

Anyways, I guess there are a few options here- I don't have strong feelings. I'm also happy with just using deferred transactions for now. What do you think?

**Comment by mgravitt** [comment]
@Gerard097 Here's the format for deferred transactions:

```
        uint64_t num_seconds_delay = current_time_point().sec_since_epoch() + c.ints.at("voting_duration_sec") + 300;
	transaction trx(num_seconds_delay);
	trx.actions.emplace_back(
		permission_level{get_self(), name("active")},
		get_self(), name("closeprop"),
		make_tuple(next_proposal_id));
	trx.delay_sec = num_seconds_delay;
	trx.send(get_next_sender_id(), get_self());
```
